trigger:
  branches:
    include:
      - main
  paths:
    include:
      - petcloudstore/petcloudstoredataops/*

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Stage
    jobs: 
      - job: BuildJob
        displayName: Build
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'petcloudstore/petcloudstoredataops'
              ArtifactName: 'petcloudstoredataops'

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: Deploy
        steps:
          - task: configuredatabricks@0
            inputs:
              url: 'https://adb-5501209530448281.1.azuredatabricks.net'
              token: $(token)
          - task: startcluster@0
            inputs:
              clusterid: '0720-145135-coup132'
          - task: deploynotebooks@0
            inputs:
              notebooksFolderPath: '$(System.DefaultWorkingDirectory)/petcloudstore/petcloudstoredataops/notebooks'
              workspaceFolder: '/prod'
