apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petcloudstoreproductservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petcloudstoreproductservice
  template:
    metadata:
      labels:
        app: aks-petcloudstoreproductservice
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        agentpool: nodepool1
      containers:
      - name: petstoreproductservice
        image: crpetcloudstore.azurecr.io/petstoreproductservice:latest
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080
        env:
          - name: PETSTOREPRODUCTSERVICE_SERVER_PORT
            value: "80"
          - name: spring.config.name
            value: application_with_everything_enabled
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: aisecretkey
                key: secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aks-petcloudstoreproductservice-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-petcloudstoreproductservice
  targetCPUUtilizationPercentage: 80 # target CPU utilization
