apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petcloudstoreorderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petcloudstoreorderservice
  template:
    metadata:
      labels:
        app: aks-petcloudstoreorderservice
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        agentpool: nodepool1
      containers:
      - name: petstoreorderservice
        image: crpetcloudstore.azurecr.io/petstoreorderservice:latest
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080
        env:
        - name: PETSTOREORDERSERVICE_SERVER_PORT
          value: "80"
        - name: spring.config.name
          value: application_with_everything_enabled
        - name: PETSTORESERVICES_AI_INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: aisecretkey
              key: secret
        - name: PETSTOREPRODUCTSERVICE_URL
          value: "http://aks-petstoreproductservice/"
        - name: PETSTOREORDERSERVICE_EMAIL_TOPIC_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: emailtopicconnstring
              key: secret
        - name: PETSTOREORDERSERVICE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: subscriptionid
              key: secret

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aks-petcloudstoreorderservice-hpa
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-petcloudstoreorderservice
  targetCPUUtilizationPercentage: 90
