#logging:
#  level:
#    org.springframework.security: DEBUG
petstore:
  service:
    url: ${PETSTORESERVICE_URL}
    subscription:
      key: ${PETSTORESERVICE_SUBSCRIPTION_KEY}
server:
  port: ${PETSTOREAPP_SERVER_PORT}
azure:
  activedirectory:
    b2c:
      tenant: fc120f97-856b-4f0c-a6a0-ad60aa98032b
      oidc-enabled: true
      client-id: 5087e542a-f20c-4f25-aa9c-1587d46f22cd
      client-secret: 7d625378-84d7-4e31-a10b-96b87d6339fc
      reply-url: https://dazharpetcloudstore.azurewebsites.net/home on Azure or Windows localhost http://localhost:8080/home
      logout-success-url: https://dazharpetcloudstore.azurewebsites.net/home on Azure or Windows localhost http://localhost:8080/home
      user-flows:
        sign-up-or-sign-in: B2C_1_signupsignin
        profile-edit: B2C_1_profileediting
        password-reset: B2C_1_passwordreset
  application-insights:
      instrumentation-key: ${PETSTORESERVICES_AI_INSTRUMENTATION_KEY}
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false  

 