#logging:
#  level:
#    org.springframework.security: DEBUG
petstore:
  service:
    url: ${PETSTORESERVICE_URL}
    subscription:
      key: ${PETSTORESERVICE_SUBSCRIPTION_KEY}
server:
  port: ${PETSTOREAPP_SERVER_PORT}
azure:
  activedirectory:
    b2c:
      tenant: fc120f97-856b-4f0c-a6a0-ad60aa98032b
      oidc-enabled: true
      client-id: 5015be0a-9c45-4821-a0dc-cacf02181571
      client-secret: d587199f-baf7-4e4f-9816-7e76b8325a49
      reply-url: https://dazharpetcloudstore.azurewebsites.net/home on Azure or Windows localhost http://localhost:8080/home
      logout-success-url: https://dazharpetcloudstore.azurewebsites.net/home on Azure or Windows localhost http://localhost:8080/home
      user-flows:
        sign-up-or-sign-in: B2C_1_signupsignin
        profile-edit: B2C_1_profileediting
        password-reset: B2C_1_passwordreset
  application-insights:
      instrumentation-key: 706772c8-6c97-4695-87c3-59c59848e4f7
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false  

 