name: Deploying Pet Cloud Store Assistant in App Service

env:
  AZURE_CONTAINER_REGISTRY: crpetcloudstore.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: crpetcloudstore

on:
  push:
    branches:
      - main
    paths:
      - petcloudstore/petcloudstoreassistant/**
  workflow_dispatch:

  repository_dispatch:
    types: [deploy-pet-cloud-store-app]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update the application.properties
      run: |
        echo -n -e "MicrosoftAppId=${{ secrets.ASSISTANTAPPID }}\nMicrosoftAppPassword=${{ secrets.ASSISTANTAPPPASSWORD }}\nserver.port=3978\napim.key=${{ secrets.ASSISTANT_APIM_KEY }}\naoai.key=${{ secrets.ASSISTANT_AOAI_KEY }}\naoai.url=https://azurepetstoreapimgmnt.azure-api.net\ncognitive.search.key=${{ secrets.ASSISTANT_CS_KEY }}\ncognitive.search.url=https://azurepetstore-cs.search.windows.net/indexes/petproducts/docs/search?api-version=2023-11-01\ncosmos.key=${{ secrets.ASSISTANT_COSMOS_KEY }}" > petcloudstore/petcloudstoreassistant/src/main/resources/application.properties
    - run: cat petcloudstore/petcloudstoreassistant/src/main/resources/application.properties
    - uses: azure/docker-login@v1
      name: Build Docker image
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.PETSTORECRSECRET }}
    - name: Build and Push Docker image to Azure Container Registry    
      run: |
        docker build petcloudstore/petcloudstoreassistant -t ${{env.AZURE_CONTAINER_REGISTRY}}/petstoreassistant:${{ github.sha }}
        docker push ${{env.AZURE_CONTAINER_REGISTRY}}/petstoreassistant:${{ github.sha }}
