name: "Main Branch Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 18 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript', 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Building Pet Store App with Java 13
      uses: actions/setup-java@v2
      with:
        java-version: '13'
        distribution: 'adopt'
    - name: Run Maven build
      run: mvn -f petcloudstore/petcloudstore/pom.xml --batch-mode --update-snapshots verify

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    # Run additional YAML files
    - name: Dispatch Deploy Pet Cloud Store App Workflow
      run: |
       curl -X POST \
       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
       -H "Accept: application/vnd.github.everest-preview+json" \
       -H "Content-Type: application/json" \
       -d '{"event_type": "deploy-pet-cloud-store-app", "client_payload": {"trigger_reason": "main-branch-build"}}' \
        https://api.github.com/repos/dazhar0/pet-cloud-shop/dispatches

      
